apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: kamczioad/idp:latest
          ports:
            - containerPort: 8083
          env:
          - name: KEYCLOAK_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: db_password
          - name: KEYCLOAK_DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: db_username
          - name: KEYCLOAK_DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: db_name
          - name: KEYCLOAK_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: admin_user
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: admin_password
          - name: KEYCLOAK_DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: keycloak-config
                key: url
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  selector:
    app: keycloak
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001